services:
  core-service-db:
    container_name: core-service-db
    image: postgres:15
    environment:
      POSTGRES_DB: core-service
      POSTGRES_USER: core-service
      POSTGRES_PASSWORD: core-service
    ports:
      - "5432:5432"
    volumes:
      - core-service-db:/var/lib/postgresql/data
  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-admin
    volumes:
      - minio-data:/data

volumes:
  core-service-db: { }
  file-storage-service-db: { }
  minio-data: { }