services:
  core-service-db:
    container_name: core-service-db
    image: postgres:15
    environment:
      POSTGRES_DB: core-service
      POSTGRES_USER: core-service
      POSTGRES_PASSWORD: core-service
    ports:
      - "5432:5432"
    volumes:
      - core-service-db:/var/lib/postgresql/data
  user-service-db:
    container_name: user-service-db
    image: postgres:15
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: user-service
    ports:
      - "5433:5432"
    volumes:
      - user-service-db:/var/lib/postgresql/data
  file-storage-db:
    container_name: file-storage-db
    image: postgres:15
    environment:
      POSTGRES_DB: file-storage-service
      POSTGRES_USER: file-storage-service
      POSTGRES_PASSWORD: file-storage-service
    ports:
      - "5434:5432"
    volumes:
      - file-storage-service-db:/var/lib/postgresql/data
  mail-service-db:
    container_name: mail-service-db
    image: mongo:8.0-rc
    ports:
      - "27017:27017"
    volumes:
      - ./config/mongo-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - mail-service-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mail-service-admin
      MONGO_INITDB_ROOT_PASSWORD: mail-service-admin
      MONGO_INITDB_USER: mail-service
      MONGO_INITDB_PWD: mail-service
      MONGO_INITDB_DATABASE: mail-service
  minio:
    container_name: minio
    image: bitnami/minio:2024.6.11
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-admin
    volumes:
      - minio-data:/data
  kafka:
    container_name: kafka
    image: "bitnami/kafka:3.7.0"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

volumes:
  core-service-db: { }
  user-service-db: { }
  file-storage-service-db: { }
  mail-service-db: { }
  minio-data: { }
  kafka-data: { }
