spring:
  application:
    name: forms
  datasource:
    url: jdbc:postgresql://localhost:5432/forms
    password: forms
    username: forms
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false