server:
  port: 8082

spring:
  application:
    name: file-storage-service
  datasource:
    url: jdbc:postgresql://localhost:5434/file-storage-service
    password: file-storage-service
    username: file-storage-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

minio:
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET:file-storage-service}
  url: ${MINIO_URL:http://localhost:9000}

security:
  common:
    autoconfigure: true
  jwt:
    autoconfigure: true
    access-token:
      public-key-name: authorization/access-token-public-key.pem
  api-key:
    autoconfigure: true
    key: ${API_KEY:api-key}