spring:
  application:
    name: file-storage-service

server:
  port: 8082

minio:
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET:file-storage-service}
  url: ${MINIO_URL:http://localhost:9000}