spring:
  application:
    name: file-storage-service
  datasource:
    url: jdbc:postgresql://localhost:5434/file-storage-service
    password: file-storage-service
    username: file-storage-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 8082

minio:
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET:file-storage-service}
  url: ${MINIO_URL:http://localhost:9000}