spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user-service
    password: user-service
    username: user-service
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8081

jwt:
  public-key-name: public-key.pem
  private-key-name: private-key.pem
  refresh-token-expiration-time-days: 7
  access-token-expiration-time-minutes: 5