spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user-service
    password: user-service
    username: user-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8081