server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user-service
    password: user-service
    username: user-service
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  access-token:
    expiration-time-minutes: 5
    public-key-name: authorization/access-token-public-key.pem
    private-key-name: authorization/access-token-private-key.pem
  refresh-token:
    expiration-time-days: 7
    private-key-name: authorization/refresh-token-private-key.pem