server:
  port: 8080

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/core-service
    password: core-service
    username: core-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

application:
  kafka:
    topic:
      send-mail: "send-mail"

security:
  common:
    autoconfigure: true
  jwt:
    autoconfigure: true
    access-token:
      public-key-name: authorization/access-token-public-key.pem
  api-key:
    autoconfigure: true
    key: ${API_KEY:api-key}