spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/core-service
    password: core-service
    username: core-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080