server:
  port: 8080

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/core-service
    password: core-service
    username: core-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

security:
  common:
    autoconfigure: true
  jwt:
    autoconfigure: true
    access-token:
      public-key-name: authorization/access-token-public-key.pem
